### PR TITLE
Created FirstScene And SecondScene classes to create a map

### PR DESCRIPTION
**Pull request by harunalbayrak**
### Description
I created FirstScene,SecondScene and some classes to create a map.

### Screenshots (If appropriate!)
Main Screen

Map

### Types of Changes

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [x] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that would cause existing functionality to
  not work as expected)
- [ ] Documentation Update
- [ ] Other (explain in detail)

### Checklist

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected misspellings

### CODE REVIEW

**Comment by repelliuss** [comment]
Images are broken to me, can you update them if you can? Also, is this a test of your work that is independent from main development? I'm just asking it cause it is in the `sample` package.

**Comment by harunalbayrak** [comment]
> Images are broken to me, can you update them if you can? Also, is this a test of your work that is independent from main development? I'm just asking it cause it is in the `sample` package.

I also updated the images but altough they are works in some markdown editors, they are being broken when i upload to github. ( 'Main Screen' )

Also, I have tested it as the main development, but I didn't delete sample folder. If you look the codes, it has been written as 'package sve.gui.sample'.

**Comment by repelliuss** [comment]
Yeah, i saw that. But it has stubs of dependencies you have like `Animal.java`. Would you want me to merge this into a new branch called something like `gui/sample` instead of `develop`?

**Comment by harunalbayrak** [comment]
> Yeah, i saw that. But it has stubs of dependencies you have like `Animal.java`. Would you want me to merge this into a new branch called something like `gui/sample` instead of `develop`?

Okey, it does not matter to me.

**Comment by repelliuss** [comment]
Okay I'll do that. I'll add prototypes of everything to work easier as soon as possible. After that you can modify what you did here and then we can merge it.

**Pull request merged**
